### ISSUE TITLE
Option to hide the toolbar on the bottom

### ISSUE THREAD

**Issue by syphernl** [CIMonitor/CIMonitor#159]
### What

Can we have an option to hide the "toolbar" on the bottom of the page? 

### Why

So that I can embed CIMonitor into an iframe. I'd like to show the last 2-3 builds but the toolbar is a bit "in the way". Might be nice to be able to hide this.

**Comment by RickvdStaaij** [comment]
Personally I'm not in favor of completely hiding it, but I understand that it's quite massive on a small device or Iframe. I would suggest adding a mini toolbar toggle in the customization settings that would look something like this:

![image](https://user-images.githubusercontent.com/6495166/74481813-ab672e80-4eb3-11ea-95fb-89b5be95029c.png)

**Comment by syphernl** [comment]
Even though the smaller would be better, it still would be "in the way" for just a small iframe (which will be big enough for the top 2-3 items). Perhaps it can be shown on mouse-move/hotcorner or something like that? I'm also fine if I could hide it using some custom CSS.

**Comment by RickvdStaaij** [comment]
@syphernl I've created https://github.com/CIMonitor/CIMonitor/pull/163 where you can enable a small sized toolbar, which only shows the status circle (green/orange/red), because I think that's an important feature that we shouldn't hide. Then you know if there is a red/orange status on your dashboard, even though you can only see the latest 2/3 statuses.

Here is what that looks like: 
![](https://user-images.githubusercontent.com/6495166/74603884-90b1d700-50b8-11ea-87f3-dcb130726211.gif)
